"""Lean4 verifier backend for the `theorem-proof` domain.

Ground-truth check: the model emits a Lean4 proof term; we write it to a
temp `.lean` file and run `lean <file>` in a subprocess. Exit 0 means
Lean accepted the proof (PASS); nonzero means Lean found a type error in
the proof (FAIL). Missing `lean` binary → graceful skip with warning.

RUN_FIRST (GPU host, to install the backend):
    curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y --default-toolchain leanprover/lean4:stable
    source $HOME/.elan/env
    lean --version   # should print "Lean (version 4.x.x, ...)"

Per §1.3 (property_engine), LEAN_PROOF is a new PropertyKind; proof.formal
is a new independence class. The builtin `_b_lean_proof_valid` is registered
automatically on import.

Per v0.2.1 §2.2, proof.formal is independent from algebra.symbolic (sympy),
smt.logical (z3), and exec.behavioral (python) — Lean's type checker is a
fundamentally different oracle.
"""

from __future__ import annotations

import logging
import re
import tempfile
from typing import Any, Optional

from .external_solver import (
    SubprocessOutcome,
    binary_available,
    run_subprocess_verifier,
)

logger = logging.getLogger(__name__)

LEAN_BINARY = "lean"
LEAN_TIMEOUT_S = 10.0

# Header prepended to every candidate proof. Keeps the proof hermetic —
# no imports mean Lean uses only its built-in prelude. Most interesting
# proofs will want `import Mathlib`, but that requires project-level lake
# scaffolding; keep this minimal and let the candidate `import` explicitly
# only if the host has Mathlib installed.
_LEAN_PRELUDE = "-- auto-generated by lean_backend.py\n"

# Candidate shapes we accept:
#   1. Bare proof term / tactic block — we wrap into `theorem <name> : <goal> := <body>`
#      if the problem ctx provides a `goal`.
#   2. A full `theorem ...` declaration emitted by the model; used as-is.
_RE_THEOREM_DECL = re.compile(r"\btheorem\s+\w+", re.MULTILINE)
_RE_LEAN_FENCE = re.compile(r"```(?:lean|lean4)?[ \t]*\n?(.*?)(?:```|\Z)", re.DOTALL)


def _extract_lean_source(candidate: Any) -> Optional[str]:
    """Pull Lean4 source out of a model response (possibly fenced)."""
    if candidate is None:
        return None
    if isinstance(candidate, str):
        text = candidate
    else:
        text = getattr(candidate, "response", "") or ""
        if not text:
            chain = getattr(candidate, "reasoning_chain", None) or []
            if chain:
                text = getattr(chain[-1], "content", "") or ""
    if not text:
        return None

    # Prefer the largest fenced block; fall back to raw text.
    best = ""
    for m in _RE_LEAN_FENCE.finditer(text):
        body = (m.group(1) or "").strip()
        if len(body) > len(best):
            best = body
    return best or text.strip()


def _wrap_if_bare(source: str, goal: Optional[str], name: str = "candidate") -> str:
    """If the source has no `theorem` keyword but the ctx supplies a goal,
    wrap it into a declaration. Otherwise return the source unchanged."""
    if _RE_THEOREM_DECL.search(source):
        return source
    if goal:
        return f"theorem {name} : {goal} := by\n  {source.strip()}\n"
    return source


def check_lean_proof(
    source: str,
    goal: Optional[str] = None,
    timeout_s: float = LEAN_TIMEOUT_S,
) -> SubprocessOutcome:
    """Run `lean` on a proof source. Returns SubprocessOutcome; `.ok` means
    the proof type-checks.

    If `goal` is provided and `source` is a bare proof body, it's wrapped
    into `theorem candidate : <goal> := by <source>`.
    """
    if not source or not source.strip():
        return SubprocessOutcome(-1, "", "empty source", 0.0)

    wrapped = _wrap_if_bare(source, goal)
    full = _LEAN_PRELUDE + wrapped + "\n"

    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".lean", delete=True, encoding="utf-8"
    ) as f:
        f.write(full)
        f.flush()
        return run_subprocess_verifier(
            [LEAN_BINARY],
            input_file=f.name,
            timeout=timeout_s,
        )


def lean_available() -> bool:
    """Is `lean` on PATH? Use this for graceful-skip branches."""
    return binary_available(LEAN_BINARY)


# ═════════════════════════════════════════════════════════════════════════
# Builtin property: lean_proof_valid
# ═════════════════════════════════════════════════════════════════════════

def _b_lean_proof_valid(problem, candidate):
    """Property-engine builtin: run candidate's Lean4 proof.

    Context keys (via property_engine.stash_problem_ctx):
      goal (str, optional) — Lean expression the proof should establish,
                             e.g. "∀ n : Nat, n + 0 = n"
      timeout_s (float, optional)

    Returns:
      (True, "")              — proof type-checks
      (False, "<lean stderr>")— proof rejected
      ("ERROR", "<reason>")   — lean not installed / no source / timeout
    """
    # Lazy import to avoid any circular dependency during property_engine load.
    from .property_engine import get_problem_ctx

    if not lean_available():
        logger.warning(
            "lean4 binary not found on PATH — property lean_proof_valid "
            "returning ERROR. Install via RUN_FIRST in lean_backend.py."
        )
        return "ERROR", "lean4 not installed"

    source = _extract_lean_source(candidate)
    if not source:
        return False, "no extractable Lean4 source in candidate"

    ctx = get_problem_ctx(problem) if problem else {}
    goal = ctx.get("goal") or None
    timeout_s = float(ctx.get("timeout_s") or LEAN_TIMEOUT_S)

    out = check_lean_proof(source, goal=goal, timeout_s=timeout_s)
    if out.missing_binary:
        return "ERROR", "lean4 not installed"
    if out.timed_out:
        return "ERROR", f"lean timeout after {timeout_s}s"
    if out.ok:
        return True, ""
    return False, f"lean rejected proof (rc={out.returncode}): {out.tail(400)}"


# Auto-register on import. Guarded so repeated imports don't re-register.
def _register() -> None:
    from . import property_engine as _pe

    # Extend enum & classes if they don't yet have our values. PropertyKind
    # is a str-Enum; we can't mutate it post-definition, so we only register
    # if the spec-level additions are already there (integration-lead merges
    # these into property_engine.py when all three verifier tasks land).
    try:
        kind = _pe.PropertyKind("LEAN_PROOF")  # type: ignore[call-arg]
    except ValueError:
        logger.info(
            "PropertyKind.LEAN_PROOF not yet present in property_engine — "
            "lean_backend builtin registration deferred. "
            "Integration-lead must add LEAN_PROOF to the PropertyKind enum."
        )
        return

    if "proof.formal" not in _pe.INDEPENDENCE_CLASSES:
        logger.info(
            "'proof.formal' not yet in INDEPENDENCE_CLASSES — registration deferred."
        )
        return

    if "lean_proof_valid" in getattr(_pe, "_BUILTIN", {}):
        return  # already registered

    _pe._register_builtin(
        name="lean_proof_valid",
        kind=kind,
        description="Candidate's Lean4 proof type-checks against the stated goal.",
        independence_class="proof.formal",
        check_fn=_b_lean_proof_valid,
        deterministic=True,
    )
    logger.info("registered builtin property: lean_proof_valid")


_register()


__all__ = [
    "LEAN_BINARY",
    "LEAN_TIMEOUT_S",
    "check_lean_proof",
    "lean_available",
]
